AWSTemplateFormatVersion: "2010-09-09"
Description: "This template creates a Multi-AZ, multi-subnet VPC infrastructure with managed NAT gateways in the public subnet for each Availability Zone. You can also create additional private subnets with dedicated custom network access control lists (ACLs). If you deploy the Quick Start in a region that doesn't support NAT gateways, NAT instances are deployed instead. **WARNING** This template creates AWS resources. You will be billed for the AWS resources used if you create a stack from this template. QS(0027)"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Availability Zone Configuration"
          Parameters:
            - AvailabilityZones
            - NumberOfAZs
      - Label:
          default: "Network Configuration"
          Parameters:
            - VPCCIDR
            - PublicSubnet1CIDR
            - PublicSubnet2CIDR
            - PublicSubnet3CIDR
            - PublicSubnet4CIDR
            - PublicSubnetTag1
            - PublicSubnetTag2
            - CreatePrivateSubnets
            - PrivateSubnet1ACIDR
            - PrivateSubnet2ACIDR
            - PrivateSubnet3ACIDR
            - PrivateSubnet4ACIDR
            - PrivateSubnetATag1
            - PrivateSubnetATag2
            - PrivateSubnetATag3
            - CreateAdditionalPrivateSubnets
            - PrivateSubnet1BCIDR
            - PrivateSubnet2BCIDR
            - PrivateSubnet3BCIDR
            - PrivateSubnet4BCIDR
            - PrivateSubnetBTag1
            - PrivateSubnetBTag2
            - PrivateSubnetBTag3
            - VPCTenancy
        - Label:
            default: "Amazon EC2 Configuration"
            Parameters:
              - KeyPairName
              - NATInstanceType

    ParameterLabels:
      AvailabilityZones:
        default: "Availability Zones"
      CreateAdditionalPrivateSubnets:
        default: "Create additional private subnets with dedicated network ACLs"
      CreatePrivateSubnets:
        default: "Create private subnets"
      KeyPairName:
        default: "Key pair name"
      NATInstanceType:
        default: "NAT instance type"
      NumberOfAZs:
        default: "Number of Availability Zones"
      PrivateSubnet1ACIDR:
        default: "Private subnet 1A CIDR"
      PrivateSubnet1BCIDR:
        default: "Private subnet 1B with dedicated network ACL CIDR"
      PrivateSubnet2ACIDR:
        default: "Private subnet 2A CIDR"
      PrivateSubnet2BCIDR:
        default: "Private subnet 2B with dedicated network ACL CIDR"
      PrivateSubnet3ACIDR:
        default: "Private subnet 3A CIDR"
      PrivateSubnet3BCIDR:
        default: "Private subnet 3B with dedicated network ACL CIDR"
      PrivateSubnet4ACIDR:
        default: "Private subnet 4A CIDR"
      PrivateSubnet4BCIDR:
        default: "Private subnet 4B with dedicated network ACL CIDR"
      PrivateSubnetATag1:
        default: "Tag for Private A Subnets"
      PrivateSubnetATag2:
        default: "Tag for Private A Subnets"
      PrivateSubnetATag3:
        default: "Tag for Private A Subnets"
      PrivateSubnetBTag1:
        default: "Tag for Private B Subnets"
      PrivateSubnetBTag2:
        default: "Tag for Private B Subnets"
      PrivateSubnetBTag3:
        default: "Tag for Private B Subnets"
      PublicSubnet1CIDR:
        default: "Public subnet 1 CIDR"
      PublicSubnet2CIDR:
        default: "Public subnet 2 CIDR"
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR"
      PublicSubnet4CIDR:
        default: "Public subnet 4 CIDR"
      PublicSubnetTag1:
        default: "Tag for Public Subnets"
      PublicSubnetTag2:
        default: "Tag for Public Subnets"
      PublicSubnetTag3:
        default: "Tag for Public Subnets"
      VPCCIDR:
        default: "VPC CIDR"
      VPCTenancy:
        default:  "VPC Tenancy"

Parameters:
  AvailabilityZones:
    Description: "List of Availability Zones to use for the subnets in the VPC. Note: The logical order is preserved."
    Type: List<AWS::EC2::AvailabilityZone::Name>
  CreateAdditionalPrivateSubnets:
    AllowedValues:
      - true
      - false
    Default: false
    Description: "Set to true to create a network ACL protected subnet in each Availability Zone. If false, the CIDR parameters for those subnets will be ignored. If true, it also requires that the 'Create private subnets' parameter is also true to have any effect."
    Type: String
  CreatePrivateSubnets:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "Set to false to create only public subnets. If false, the CIDR parameters for ALL private subnets will be ignored."
    Type: String
  KeyPairName:
    Description: "Public/private key pairs allow you to securely connect to your NAT instance after it launches. This is used only if the region does not support NAT gateways."
    Type: AWS::EC2::KeyPair::KeyName
  NATInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m3.medium
      - m3.large
      - m4.large
    Default: t2.small
    Description: "Amazon EC2 instance type for the NAT instances. This is used only if the region does not support NAT gateways."
    Type: String
  NumberOfAZs:
    AllowedValues:
      - 2
      - 3
      - 4
    Default: 3
    Description: "Number of Availability Zones to use in the VPC. This must match your selections in the list of Availability Zones parameter."
    Type: String
  PrivateSubnet1ACIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.0.0/19"
    Description: "CIDR block for private subnet 1A located in Availability Zone 1",
    Type: String
  PrivateSubnet1BCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.192.0/21"
    Description: "CIDR block for private subnet 1B with dedicated network ACL located in Availability Zone 1"
    Type: String
  PrivateSubnet2ACIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.32.0/19"
    Description: "CIDR block for private subnet 2A located in Availability Zone 2"
    Type: String
  PrivateSubnet2BCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.200.0/21"
    Description: "CIDR block for private subnet 2B with dedicated network ACL located in Availability Zone 2"
    Type: String
  PrivateSubnet3ACIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.64.0/19"
    Description: "CIDR block for private subnet 3A located in Availability Zone 3"
    Type: String
  PrivateSubnet3BCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.208.0/21"
    Description: "CIDR block for private subnet 3B with dedicated network ACL located in Availability Zone 3"
    Type: String
  PrivateSubnet4ACIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.96.0/19"
    Description: "CIDR block for private subnet 4B with dedicated network ACL located in Availability Zone 4"
    Type: String
  PrivateSubnet1ACIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-28"
    Default: "10.0.0.0/19"
    Description: "CIDR block for private subnet 1A located in Availability Zone 1",
    Type: String
